Use unicode instead of string for writing files
Fix the following error: 

```
File "~/machine_translation/dataprocessor.py", line 268, in write_sentences
    of.write(sent + '\n')
TypeError: must be unicode, not str
```